name: Browser test

on:
  pull_request:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  browsers-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
      - name: Install firefox
        run: brew install --cask firefox
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run browser tests
        env:
          FIREFOX_BIN: /Applications/Firefox.app/Contents/MacOS/firefox
        run: npm run test:karma
