name: Node.JS test and lint

on:
  pull_request:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  nodejs-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Remember to update README.md and package.json when updating the version matrix
        version: [22, 23, 24]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Unit tests
        run: npm run test:node
      - name: Coveralls
        if: ${{ success() }}
        uses: coverallsapp/github-action@master
        with:
          parallel: true
          flag-name: node-${{ matrix.version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./coverage/lcov.info"

  finish:
    needs: nodejs-test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
