name: Publish tag to npm

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Smoke Test
        run: npm run test:node
      - name: Publish to npm
        run: npm publish
